robot_reach_study_node:
  ros__parameters:
    config_name: "demo_config"
    object_frame: "reach_object"
    results_package: "reach_demo"
    results_directory: "results"
    pcd_package: "reach_demo"
    pcd_filename_path: "config/part.pcd"
    get_avg_neighbor_count: false
    compare_dbs: [""]
    visualize_results: true
    planning_groups: ["manipulator"]
    run_initial_study_only: false

    optimization:
      radius: 0.2
      max_steps: 10
      step_improvement_threshold: 0.01

    ik_solver_config:
      name: "moveit_reach_plugins/ik/MoveItIKSolver"
      distance_threshold: 0.0
      planning_groups: ["manipulator"]
      collision_mesh_package: "reach_demo"
      collision_mesh_filename_path: "config/part.ply"
      collision_mesh_frame: "reach_object"
      touch_links: [""]
      evaluation_plugin:
        name: "reach_core/plugins/MultiplicativeFactory"
        plugins: ["moveit_reach_plugins/evaluation/ManipulabilityMoveIt", "moveit_reach_plugins/evaluation/DistancePenaltyMoveIt"]
        moveit_reach_plugins/evaluation/ManipulabilityMoveIt:
          planning_groups: ["manipulator"]
        moveit_reach_plugins/evaluation/DistancePenaltyMoveIt:
          planning_groups: ["manipulator"]
          distance_threshold: 0.025
          exponent: 2
          collision_mesh_package: "package://reach_demo/config/part.ply"
          collision_mesh_package: "reach_demo"
          collision_mesh_filename_path: "config/part.ply"
          touch_links: [""]

    display_config:
      name: "moveit_reach_plugins/display/MoveItReachDisplay"
      planning_groups: ["manipulator"]
      collision_mesh_package: "reach_demo"
      collision_mesh_filename_path: "config/part.ply"
      collision_mesh_frame: "reach_object"
      marker_scale: 0.05
